---
# Define the project settings
deployment:
  tasks:
    - export DEPLOYPATH=/home/digiadmin/public_html
    - /bin/cp -R . $DEPLOYPATH
    - echo "Starting deployment..."


    # Step 1: Navigate to the deployment directory
    - cd $DEPLOYPATH || exit 1

    # Step 2: Install Node.js dependencies
    - npm install --production

    # Step 4: Restart the Node.js application
    - pm2 restart all

    - echo "Deployment completed successfully."